package ru.yandex.practicum.taskTracker.http;

public enum Endpoint {
    GET_PRIORITIZES_TASKS,
    GET_HISTORY,
    GET_SUBTASKS_FROM_EPIC,
    GET_ALL_TASKS,
    GET_TASK_BY_ID,
    POST_TASK,
    DELETE_ALL_TASKS,
    DELETE_TASK_BY_ID,
    GET_ALL_EPICS,
    GET_EPIC_BY_ID,
    POST_EPIC,
    DELETE_ALL_EPICS,
    DELETE_EPIC_BY_ID,
    GET_ALL_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_SUBTASK,
    DELETE_ALL_SUBTASKS,
    DELETE_SUBTASK_BY_ID,
    UNKNOWN
}
